### ISSUE TITLE
Slf4j의 구현체를 logback에서 log4j2로 전환한다

### ISSUE THREAD

**Issue by woong7** [woowacourse-teams/2022-review-duck#118]

**Comment by ulimy** [comment]
해당 이슈를 등록할 시점에서는 log4j2가 더 성능이 높다고 판단했습니다.
하지만 추가 조사 결과 멀티 쓰레드 환경에서 비동기 로거(Async Logger)의 경우에만 Log4j 1.x 및 Logback보다 처리량이 18배 더 높고 대기 시간이 훨씬 더 짧다는 것을 확인했습니다.
회고덕의 경우 비동기 로거를 사용하고 있지 않기 때문에 logback으로 유지하겠습니다!
