### ISSUE TITLE
Query Hook에 데이터 가공 레이어를 추가한다.

### ISSUE THREAD

**Issue by compy-ryu** [woowacourse-teams/2022-review-duck#295]
## 문제점
- 현재 페이지 컴포넌트들은 API에 상당히 의존적인 상황.
- API 명세가 변경되었을 때, 해당 API를 사용하는 페이지 컴포넌트들 또한 모두 수정이 이뤄져야함.
- 프론트엔드는 API의 작은 변경사항에도, API의 사용 빈도에 따라 큰 영향을 받게 될 수 있어
이는 유지/보수에 좋지 않은 구조라 생각됨.

## 해결책 제안
- React Query에서 제공하는 `useQuery`의 select 옵션을 활용하여
데이터를 사전에 프론트엔드에서 사용하는 규격으로 가공하여 페이지 컴포넌트에서 활용.

- 추후 API 명세가 변경되어도 Query Hook에서 일괄적으로 대응할 수 있게됨.

- 페이지 컴포넌트는 useQuery에서 이미 데이터를 가공한 결과를 받아 사용하기에
기존 규격을 그대로 따를 수 있어 수정이 필요 없음.

**Comment by compy-ryu** [comment]
스프린트 기간 중에는 실제 작업하는 도메인에서 위 사항을 반영하되
일괄적인 변경은 레벨 4 리팩토링 기간에 진행합니다.

**Comment by DomMorello** [comment]
해당 이슈는 transformer 규격을 만드는 것으로 해결됐으니 닫겠습니다 :)
