### ISSUE TITLE
템플릿으로 회고하기 클릭 후 취소하기를 누르면 오류 발생하는 버그

### ISSUE THREAD

**Issue by woong7** [woowacourse-teams/2022-review-duck#464]

**Comment by RunaNam** [comment]
수정 방향 : 제출 버튼을 눌렀을 때 회고 폼과 회고 답변이 한번에 생성되도록한다. 
다만, 프론트앤드의 페이지 재사용에서 문제가 발생하지 않을지 고민이 더 필요하므로 잠깐 미뤄두기!

**Comment by compy-ryu** [comment]
* 확인해보니, 리턴 처리가 안되어있었네요! 해-결
