### ISSUE TITLE
오버뷰에서 회고에 참여한 사람이 많지 않아도 화살표가 존재하는 버그

### ISSUE THREAD

**Issue by ulimy** [woowacourse-teams/2022-review-duck#470]
<img width="644" alt="스크린샷 2022-09-26 오후 3 32 49" src="https://user-images.githubusercontent.com/18046394/192208377-a43f6b93-a505-4875-a863-0ea865d229cc.png">

**Comment by compy-ryu** [comment]
* ScrollPanel 컴포넌트 버그였습니다! 해결했어요! 곧 PR 날릴 예정!
