### ISSUE TITLE
오버뷰의 회고에 참여한 사람에서 첫번째 사람의 프로필 사진의 오른쪽 부분에만 프로필 링크가 있는 버그

### ISSUE THREAD

**Issue by ulimy** [woowacourse-teams/2022-review-duck#471]
- 왼쪽 ( 눌러도 아무 일도 안일어남 )
![51F50C71-2A20-4D70-B874-B50FB85CB909_1_102_o](https://user-images.githubusercontent.com/18046394/192209353-d1901a0c-74e7-4ae0-868a-420f99ad1305.jpeg)

- 오른쪽 ( 프로필로 이동 )
![34992EC6-D84C-4CC1-BD48-81745E403F92](https://user-images.githubusercontent.com/18046394/192209367-5cfd0f2c-0519-431f-814d-31f2d10d8332.jpeg)

2번째 사람부터는 전체 사진에 정상적으로 적용되어있습니다!

**Comment by compy-ryu** [comment]
* 해당 부분은 ScrollPanel 컴포넌트의 버그였습니다! 현재 해결했고, 곧 PR 제출해서 머지할 예정입니다!
