### ISSUE TITLE
템플릿 페이지 내에서 각 로고의 크기가 일정하지 않은 버그

### ISSUE THREAD

**Issue by RunaNam** [woowacourse-teams/2022-review-duck#473]
![image](https://user-images.githubusercontent.com/54093525/192209613-13f01026-bc4b-415f-a301-f99c911b9b88.png)

**Comment by compy-ryu** [comment]
* 템플릿 디테일 페이지 디자인이 변경됨에 따라 해당 이슈 해결 완료했습니더!
