### ISSUE TITLE
템플릿 페이지에서 목록을 클릭하였을 경우 무조건 트랜딩으로 가는 버그

### ISSUE THREAD

**Issue by RunaNam** [woowacourse-teams/2022-review-duck#474]
의도한 것인지는 모르겠으나 템플릿 스토어에서 템플릿으로 들어가고, 그 이후 목록을 누르면 그전에 보던 화면이 최신순이어도 무조건 트랜딩으로 연결됩니다.

**Comment by compy-ryu** [comment]
* 템플릿 목록 -> 템플릿 상세 조회 -> 다시 목록으로 이동 시 필터 유지되도록 했습니다!
