### ISSUE TITLE
참여코드로 입장되지 않는 버그

### ISSUE THREAD

**Issue by ulimy** [woowacourse-teams/2022-review-duck#475]
이미 존재하는 참여코드를 복사 붙여넣기 하였음에도 참여가 되지 않습니다. 네트워크 요청도 오지 않네요ㅠㅠ
참여코드에 따라 되는 것도 있고 안되는 것도 있습니다..

<img width="1512" alt="스크린샷 2022-09-26 오후 3 45 02" src="https://user-images.githubusercontent.com/18046394/192210701-3966e31e-51ca-444d-bd4b-1d8e10dfeaff.png">

**Comment by ulimy** [comment]
참여코드에 따라 되는 것도 있고 안되는 것도 있습니다..

**Comment by DomMorello** [comment]
@compy-ryu 정규식 손 봐주시면 될 것 같습니다!
