### ISSUE TITLE
버튼 네이밍 관련 고민

### ISSUE THREAD

**Issue by ulimy** [woowacourse-teams/2022-review-duck#477]
- 회고폼을 수정하는 버튼 이름이 질문 수정이 괜찮을까? 질문지 수정이 맞지 않을까? 그 위에도 회고관리라고 적혀있다. 회고질문지 관리가 맞을듯..!
- 마이페이지에서 회고, 회고폼, 템플릿에 대한 수정삭제 버튼이 모두 회고편집, 회고삭제라는 이름으로 구현되어있다.

**Comment by compy-ryu** [comment]
* 편집 및 삭제 버튼, 링크들의 텍스트를 일괄적으로 편집/삭제로 통일해서 네이밍 고민을 제거했습니다.
  * 질문 수정 => (아이콘) 수정 / 회고 삭제 => (아이콘) 삭제
