### ISSUE TITLE
마이페이지와 템플릿 최신순의 정렬 기준을 updateAt이 아닌 createdAt으로 변경한다.

### ISSUE THREAD

**Issue by ulimy** [woowacourse-teams/2022-review-duck#478]

**Comment by woong7** [comment]
`TemplateSortType`과 `ReviewSortType`의 `LATEST`를 updatedAt -> createdAt 기준으로 변경하고, 
`ReviewSortType`에 updatedAt 기준 정렬을 의미하는 `UPDATE`를 추가하였습니다.
