### ISSUE TITLE
템플릿 생성할 시 아무 것도 보이지 않는 오류

### ISSUE THREAD

**Issue by sojukang** [woowacourse-teams/2022-review-duck#500]
![image](https://user-images.githubusercontent.com/83529599/193980673-c4d58502-86d3-447f-9e4f-f8f2d7f0fecd.png)

아무 것도 표시되지 않습니다 ㅠㅠ

**Comment by DomMorello** [comment]
현재 콤피가 작업중인 부분입니다!
