### ISSUE TITLE
유저 프로필 페이지 article 좋아요 0인 경우 출력 오류

### ISSUE THREAD

**Issue by sojukang** [woowacourse-teams/2022-review-duck#564]
![image](https://user-images.githubusercontent.com/83529599/196009384-52fad0f1-7687-4fe9-b92c-240c05decd2c.png)

article.likes 가 0일 때 분기 처리에 오류가 있는 것 같습니다!

**Comment by compy-ryu** [comment]
develop에서 이미 고쳐진 버그라 이슈 닫겠습니다!
